apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-scripts-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 